from typing import Any, Protocol


class HTTPClient(Protocol):
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def post(self, *args: Any, **kwargs: Any) -> Any: ...
    def patch(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...
